from sqlalchemy import Column, Integer, String, Text, ForeignKey
from database import Base

class User(Base):
    """
    Represents a user in the database.
    Attributes:
        id (int): The primary key for the user.
        username (str): The unique username of the user.
        password (str): The password of the user.
    """
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    password = Column(String)

class Conversation(Base):
    """
    Represents a conversation between a user and the system.
    Attributes:
        id (int): The primary key of the conversation.
        user_id (int): The foreign key referencing the user involved in the conversation.
        message (str): The message sent by the user.
        response (str): The response generated by the system.
    """
    __tablename__ = "conversations"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    message = Column(Text)
    response = Column(Text)
